### ISSUE TITLE
Account von Blink wurde gesperrt.

### ISSUE THREAD

**Issue by xxsirosxx** [Flashy-GER/ioBroker.blink4home#13]
Mein Account wurde heute von Blink gesperrt.
Sie haben festgestellt das eine Anwendung meine Blink System scharf und Unscharf stellt.

**Hier noch die Originale Mail.**

Hi,

We hope this email finds you well, We have noted that your account is running some third party automation system that controls arming and disarming function of the blink system, Since these automatons are not supported, your account access has been temporarily deactivated. We recommend removing this automation immediately in order to have your account re-activated. Please let us know once the automation is removed so we can restore your access to the system.

Thank you very much for your cooperation

Technical Support Engineer

**Comment by Flashy-GER** [comment]
Hi,
ich würde mich nochmal an deiner Stelle an den Support oder Kundenservice wenden, was das soll, denn Blink stellt ja extra für solche Funktionen eine REST API zur Verfügung, die ich u.a. ja auch für den Adapter nutze und auch viele andere. Deshalb verstehe ich nicht warum dein Account gesperrt wurde. Bis jetzt habe ich noch von keinem solch einem Fall gehört.

**Comment by xxsirosxx** [comment]
Hallo
Nach langen hin und her mit Amazon und Blink ist heute wieder alles freigeschaltet.
Der Support von Blink hat mir das noch geschickt.

`Please could you confirm disabling that third party app, otherwise the server will automatically disable the account again.
Technical Support Engineer
`
Ich weiß nicht wie die das feststellen konnten oder immer noch können.

`Mein Aufbau im Iobroker ist so:
Ich verwende deinen und den Ping Adapter .
Ping sagt ich bin Zuhause und mit deinem Adapter wird Blink ausgeschalten.`

Wo die jetzt das Problem sehen verstehe ich nicht.
Vielleicht kannst du mir da noch weiterhelfen.
Wenn du willst kann ich dir noch den Kontakt zukommen lassen.

**Comment by xxsirosxx** [comment]
![IMG_20200401_203405](https://user-images.githubusercontent.com/55346205/78173522-25e61080-7458-11ea-9389-78b4a74fc67b.jpg)

**Comment by Flashy-GER** [comment]
Hi, 
aus meiner Sicht, machst Du hier nichts falsch. 
Ich kann nicht glauben, das es am iobroker liegen soll, denn diesen Weg nutzen sehr viele User, um die  Kamera zu steuern, also nicht nur über iobroker, sondern auch bei OpenHub oder anderen smarthome Anwendungen, sogar über den Homekit wird der Adapter so benutzt. Es gibt auch noch echte 3-Anbieter Apps über den Google oder Apple Store für die Steuerung, evtl. ist so eine App dafür verantwortlich. oder jemand anders nutzt deinen Account über eine andere App, kann natürlich auch sein.

**Comment by RP70DP** [comment]
Ich habe heute folgende E-Mail erhalten:

Dear Blink Customer,
 
You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11.

**Comment by Flashy-GER** [comment]
see
https://github.com/Flashy-GER/ioBroker.blink4home/issues/15
