### ISSUE TITLE
Adapter legt keine Datenpunkte an

### ISSUE THREAD

**Issue by eifeler-thd** [Flashy-GER/ioBroker.blink4home#2]
Der Adapter legt keine Datenpunkte an. 
Auch zeigt der Adapter grün an, wenn man falsche Logindaten angibt.

**Comment by Flashy-GER** [comment]
bin grad am Update der Komponenten, deshalb funktioniert das manchmal nicht mehr. aktuell funktioniert nun das Anlegen der Datenpunkte wieder. bitte mal testen.
Das mit der Abfrage der Login Daten bei Adapter Start muss ich noch einbauen.

**Comment by eifeler-thd** [comment]
Die Datenpunkte werden jetzt angelegt. Den Adapter musste ich löschen, wieder installieren und aktivieren. Ein bloßes darüberschreiben hat nicht funktioniert.
Der Datenpunkt „armed“ sollte noch auf schreibend gesetzt werden, sonst läßt sich dieser nicht setzen.
Neben dem globalen aktivieren (armed) und deaktivieren (disarmed) der Kameras, ließe sich das auch einzeln für die Kameras bewerkstelligen. Das hatte ich scriptgesteuert schonmal getestet.

**Comment by Flashy-GER** [comment]
die Datenpunkte lasse ich erstmal lesend, Man kann ja die Werte unabhängig von den Schreibrechten über Javascript oder Blockly trotzdem überschreiben (anstonsten kannst Du Dir ja vorerst das Schreibrecht auf den Datenpunkt selber setzen). Aktuell wird das globale arm/disarm unterstützt. Mehr Funktionalität würde ich vorerst in die Weboberfläche integrieren  wollen.
Kameraabhängig ist glaube ich nur das MotionDetection ein und auszuschalten möglich.
